PaleoSpin.proteins = [
  {name: 'Bacon', enabled: true},
  {name: 'Bass', enabled: true},
  {name: 'Bison', enabled: true},
  {name: 'Beef ribs', enabled: true},
  {name: 'Beef roast', enabled: true},
  {name: 'Beef stew meat', enabled: true},
  {name: 'Catfish', enabled: true},
  {name: 'Chicken breast', enabled: true},
  {name: 'Chicken thighs', enabled: true},
  {name: 'Chicken wings', enabled: true},
  {name: 'Chicken legs', enabled: true},
  {name: 'Clams', enabled: true},
  {name: 'Eggs', enabled: true},
  {name: 'Flounder', enabled: true},
  {name: 'Ground beef', enabled: true},
  {name: 'Grouper', enabled: true},
  {name: 'Halibut', enabled: true},
  {name: 'Lamb chops', enabled: true},
  {name: 'Lamb rack', enabled: true},
  {name: 'Lobster', enabled: true},
  {name: 'Mackerel', enabled: true},
  {name: 'Mahi Mahi', enabled: true},
  {name: 'Mussels', enabled: true},
  {name: 'Oysters', enabled: true},
  {name: 'Pork loin', enabled: true},
  {name: 'Pork chop', enabled: true},
  {name: 'Pork ribs', enabled: true},
  {name: 'Pork roast', enabled: true},
  {name: 'Trout', enabled: true},
  {name: 'Salmon', enabled: true},
  {name: 'Sardines', enabled: true},
  {name: 'Scallops', enabled: true},
  {name: 'Shrimp', enabled: true},
  {name: 'Snapper', enabled: true},
  {name: 'Steak, ribeye', enabled: true},
  {name: 'Steak, new york strip', enabled: true},
  {name: 'Steak, t-bone', enabled: true},
  {name: 'Turkey', enabled: true},
  {name: 'Tuna', enabled: true},
];
