PaleoSpin.proteins = [
  {name: 'Chicken breast', enabled: true},
  {name: 'Chicken thigh', enabled: true},
  {name: 'Eggs', enabled: true},
  {name: 'Flounder', enabled: true},
  {name: 'Snapper', enabled: true},
  {name: 'Trout', enabled: true},
  {name: 'Halibut', enabled: true},
  {name: 'Mackerel', enabled: true},
  {name: 'Bass', enabled: true},
  {name: 'Salmon steak', enabled: true},
  {name: 'Salmon fillet', enabled: true},
  {name: 'Shrimp', enabled: true},
  {name: 'New York steak', enabled: true},
  {name: 'Rib eye steak', enabled: true},
  {name: 'Round steak', enabled: true},
  {name: 'Ground beef', enabled: true},
  {name: 'Beef ribs', enabled: true},
  {name: 'Rump roast', enabled: true},
  {name: 'Beef stew meat', enabled: true},
  {name: 'Pork loin', enabled: true},
  {name: 'Pork chop', enabled: true},
  {name: 'Pork ribs', enabled: true},
  {name: 'Baby back ribs', enabled: true},
  {name: 'Bacon', enabled: true},
  {name: 'Pork roast', enabled: true},
  {name: 'Lamb chops', enabled: true},
  {name: 'Lamb rack', enabled: true},
  {name: 'Venison steaks', enabled: true}
];
