PaleoSpin.proteins = [
  'Chicken breast',
  'Chicken thigh',
  'Flounder',
  'Snapper',
  'Trout',
  'Halibut',
  'Mackerel',
  'Bass',
  'Salmon steak',
  'Salmon fillet',
  'Shrimp',
  'New York steak',
  'Rib eye steak',
  'Round steak',
  'Ground beef',
  'Beef ribs',
  'Rump roast',
  'Beef stew meat',
  'Pork loin',
  'Pork chop',
  'Pork ribs',
  'Baby back ribs',
  'Bacon',
  'Pork roast',
  'Lamb chops',
  'Lamb rack',
  'Venison steaks',
  'Eggs'
];
