PaleoSpin.spices = [
  {name: 'Allspice', enabled: true},
  {name: 'Anise', enabled: true},
  {name: 'Annatto', enabled: true},
  {name: 'Basil', enabled: true},
  {name: 'Bay Leaf', enabled: true},
  {name: 'Caraway', enabled: true},
  {name: 'Cardamom', enabled: true},
  {name: 'Cayenne pepper', enabled: true, nightshade: true},
  {name: 'Celery seed', enabled: true},
  {name: 'Chervil', enabled: true},
  {name: 'Chicory', enabled: true, fodmap: true},
  {name: 'Chili powder', enabled: true, nightshade: true},
  {name: 'Chives', enabled: true},
  {name: 'Cilantro', enabled: true},
  {name: 'Cinnamon', enabled: true},
  {name: 'Clove', enabled: true},
  {name: 'Coriander', enabled: true},
  {name: 'Cumin', enabled: true},
  {name: 'Curry-Red', enabled: true},
  {name: 'Curry-Green', enabled: true},
  {name: 'Curry-Yellow', enabled: true},
  {name: 'Dill', enabled: true},
  {name: 'Fennel', enabled: true, fodmap: true},
  {name: 'Fenugreek', enabled: true},
  {name: 'Garam Masala', enabled: true},
  {name: 'Garlic', enabled: true},
  {name: 'Ginger', enabled: true},
  {name: 'Herbs de Provance', enabled: true},
  {name: 'Horseradish', enabled: true, fodmap: true},
  {name: 'Lavender', enabled: true},
  {name: 'Lemongrass', enabled: true},
  {name: 'Majoram', enabled: true},
  {name: 'Mint', enabled: true},
  {name: 'Mustard', enabled: true},
  {name: 'Nutmeg', enabled: true},
  {name: 'Oregano', enabled: true},
  {name: 'Paprika', enabled: true, nightshade: true},
  {name: 'Parsley', enabled: true},
  {name: 'Pepper, black', enabled: true},
  {name: 'Peppermint', enabled: true},
  {name: 'Rosemary', enabled: true},
  {name: 'Tarragon', enabled: true},
  {name: 'Thyme', enabled: true},
  {name: 'Turmeric', enabled: true},
  {name: 'Wasabi', enabled: true, fodmap: true, goitrogen: true}
]
