PaleoSpin.spices = [
  {name: 'Allspice', enabled: true},
  {name: 'Basil', enabled: true},
  {name: 'Cardamom', enabled: true},
  {name: 'Cinnamon', enabled: true},
  {name: 'Celery seed', enabled: true},
  {name: 'Dill', enabled: true},
  {name: 'Fenugreek', enabled: true},
  {name: 'Garlic', enabled: true},
  {name: 'Ginger', enabled: true},
  {name: 'Curry-Red', enabled: true},
  {name: 'Curry-Green', enabled: true},
  {name: 'Curry-Yellow', enabled: true},
  {name: 'Oregano', enabled: true},
  {name: 'Cilantro', enabled: true},
  {name: 'Nutmeg', enabled: true},
  {name: 'Rosemary', enabled: true},
  {name: 'Thyme', enabled: true},
  {name: 'Garam Masala', enabled: true},
  {name: 'Bay Leaf', enabled: true},
  {name: 'Salt', enabled: true},
  {name: 'Herbs de Provance', enabled: true},
  {name: 'Chili powder', enabled: true},
  {name: 'Paprika', enabled: true},
  {name: 'Cumin', enabled: true},
  {name: 'Black pepper', enabled: true}
]
