PaleoSpin.veggies = [
  {name: 'Asparagus', enabled: true},
  {name: 'Avocado', enabled: true},
  {name: 'Artichoke hearts', enabled: true},
  {name: 'Brussels sprouts', enabled: true},
  {name: 'Carrots', enabled: true},
  {name: 'Celery', enabled: true},
  {name: 'Daikon', enabled: true},
  {name: 'Zucchini', enabled: true},
  {name: 'Fennel Root', enabled: true},
  {name: 'Kale', enabled: true},
  {name: 'Chard', enabled: true},
  {name: 'Dandelion greens', enabled: true},
  {name: 'Spinach', enabled: true},
  {name: 'Red pepper', enabled: true},
  {name: 'Yellow pepper', enabled: true},
  {name: 'Green pepper', enabled: true},
  {name: 'Red cabbage', enabled: true},
  {name: 'Green cabbage', enabled: true},
  {name: 'Napa cabbage', enabled: true},
];

