PaleoSpin.veggies = [
  {name: 'Artichokes', enabled: true, fodmap: true},
  {name: 'Asparagus', enabled: true, fodmap: true},
  {name: 'Arugula', enabled: true},
  {name: 'Avocado', enabled: true, fodmap: true},
  {name: 'Bamboo shoots', enabled: true},
  {name: 'Beets', enabled: true, starch: true, fodmap: true},
  {name: 'Bok choy', enabled: true, goitrogen: true},
  {name: 'Broccoli', enabled: true, fodmap: true, goitrogen: true},
  {name: 'Brussels sprouts', enabled: true, fodmap: true, goitrogen: true},
  {name: 'Cabbage, red', enabled: true, fodmap: true, goitrogen: true},
  {name: 'Cabbage, green', enabled: true, fodmap: true, goitrogen: true},
  {name: 'Cabbage, napa', enabled: true, fodmap: true, goitrogen: true},
  {name: 'Carrots', enabled: true},
  {name: 'Cauliflower', enabled: true, fodmap: true, goitrogen: true},
  {name: 'Celery', enabled: true},
  {name: 'Chard', enabled: true},
  {name: 'Collard Greens', enabled: true, goitrogen: true},
  {name: 'Cucumbers', enabled: true},
  {name: 'Daikon', enabled: true},
  {name: 'Dandelion greens', enabled: true, fodmap: true},
  {name: 'Eggplant', enabled: true, nightshade: true, fodmap: true},
  {name: 'Endive', enabled: true},
  {name: 'Fennel', enabled: true, fodmap: true},
  {name: 'Green beans', enabled: true},
  {name: 'Green onions', enabled: true, fodmap: true},
  {name: 'Jicama', enabled: true, fodmap: true},
  {name: 'Kale', enabled: true, goitrogen: true},
  {name: 'Leeks', enabled: true, fodmap: true},
  {name: 'Lettuce', enabled: true},
  {name: 'Mushrooms', enabled: true, fodmap: true},
  {name: 'Mustard Greens', enabled: true, fodmap: true},
  {name: 'Okra', enabled: true, fodmap: true},
  {name: 'Onions', enabled: true, fodmap: true},
  {name: 'Parsnips', enabled: true},
  {name: 'Peppers, red', enabled: true, nightshade: true, fodmap: true},
  {name: 'Peppers, yellow', enabled: true, nightshade: true, fodmap: true},
  {name: 'Peppers, green', enabled: true, nightshade: true, fodmap: true},
  {name: 'Radicchio', enabled: true},
  {name: 'Radishes', enabled: true, goitrogen: true},
  {name: 'Rapini', enabled: true, goitrogen: true},
  {name: 'Rutabagas', enabled: true},
  {name: 'Snap peas', enabled: true},
  {name: 'Spinach', enabled: true, goitrogen: true},
  {name: 'Squash, acorn', enabled: true, starch: true},
  {name: 'Squash, butternut', enabled: true, starch: true},
  {name: 'Sweet Potatoes', enabled: true, starch: true, goitrogen: true},
  {name: 'Tomatillos', enabled: true, nightshade: true},
  {name: 'Tomatoes', enabled: true, nightshade: true},
  {name: 'Turnip Greens', enabled: true},
  {name: 'Turnips', enabled: true},
  {name: 'Watercress', enabled: true, goitrogen: true},
  {name: 'Yams', enabled: true, starch: true},
  {name: 'Yuccas', enabled: true, starch: true},
  {name: 'Zucchini', enabled: true},
];
